'use client';

import { useState, useEffect } from 'react';

interface Battle {
  id: string;
  symbol: string;
  commentary: string | null;
  bot1_name: string;
  bot2_name: string;
  winner_name: string | null;
  bot1_action: string;
  bot2_action: string;
  bot1_pnl: number;
  bot2_pnl: number;
  resolved_at: string;
}

interface BattleCommentaryProps {
  /** If provided, shows commentary for a specific battle. Otherwise auto-fetches latest. */
  battleId?: string;
  className?: string;
}

export function BattleCommentary({ battleId, className = '' }: BattleCommentaryProps) {
  const [battle, setBattle] = useState<Battle | null>(null);
  const [loading, setLoading] = useState(true);
  const [idx, setIdx] = useState(0);
  const [battles, setBattles] = useState<Battle[]>([]);

  useEffect(() => {
    async function load() {
      try {
        if (battleId) {
          const res = await fetch(`/api/battles/${battleId}/commentary`);
          if (res.ok) {
            const data = await res.json();
            if (data.success) setBattle(data);
          }
        } else {
          const res = await fetch('/api/battles/latest');
          if (res.ok) {
            const data = await res.json();
            if (data.success && data.battles?.length) {
              // Filter to ones with commentary first, then fallback to any
              const withComm = data.battles.filter((b: Battle) => b.commentary);
              const list = withComm.length > 0 ? withComm : data.battles;
              setBattles(list);
              setBattle(list[0]);
            }
          }
        }
      } catch (e) {
        console.error('[BattleCommentary]', e);
      }
      setLoading(false);
    }
    load();
    // Refresh every 2 minutes
    const interval = setInterval(load, 2 * 60 * 1000);
    return () => clearInterval(interval);
  }, [battleId]);

  // Cycle through battles every 30s if multiple
  useEffect(() => {
    if (battles.length <= 1) return;
    const t = setInterval(() => {
      setIdx(i => {
        const next = (i + 1) % battles.length;
        setBattle(battles[next]);
        return next;
      });
    }, 30 * 1000);
    return () => clearInterval(t);
  }, [battles]);

  if (loading) {
    return (
      <div className={`bg-gray-900/60 border border-gray-800 rounded-xl p-4 animate-pulse ${className}`}>
        <div className="h-4 bg-gray-800 rounded w-1/3 mb-3" />
        <div className="h-3 bg-gray-800 rounded w-full mb-2" />
        <div className="h-3 bg-gray-800 rounded w-5/6" />
      </div>
    );
  }

  if (!battle) return null;

  // Strip the "🤖 Powered by ChainGPT AI" suffix for separate display
  const rawCommentary = battle.commentary || '';
  const badgeSuffix = '\n\n🤖 Powered by ChainGPT AI';
  const commentaryText = rawCommentary.endsWith('🤖 Powered by ChainGPT AI')
    ? rawCommentary.slice(0, rawCommentary.lastIndexOf('\n\n🤖 Powered by ChainGPT AI'))
    : rawCommentary;

  return (
    <div className={`relative bg-gradient-to-br from-gray-900/90 to-gray-950/90 border border-cyan-500/20 rounded-xl overflow-hidden ${className}`}>
      {/* Header glow bar */}
      <div className="h-px bg-gradient-to-r from-transparent via-cyan-400/60 to-transparent" />

      <div className="p-4 sm:p-5">
        {/* Title row */}
        <div className="flex items-center gap-2 mb-3">
          <span className="text-lg">🎙️</span>
          <span className="text-xs font-bold text-cyan-400 uppercase tracking-wider">AI Battle Commentary</span>
          {battles.length > 1 && (
            <span className="ml-auto text-xs text-gray-600">{idx + 1}/{battles.length}</span>
          )}
        </div>

        {/* Battle header */}
        <div className="flex items-center gap-2 mb-3 text-sm">
          <span className="font-mono text-xs bg-gray-800 text-gray-300 px-2 py-0.5 rounded">{battle.symbol}</span>
          <span className="font-semibold text-white">{battle.bot1_name}</span>
          <span className="text-gray-600 text-xs">⚔️</span>
          <span className="font-semibold text-white">{battle.bot2_name}</span>
          {battle.winner_name && (
            <>
              <span className="text-gray-600 ml-1">→</span>
              <span className="text-yellow-400 font-bold text-xs">🏆 {battle.winner_name}</span>
            </>
          )}
        </div>

        {/* Commentary text */}
        {commentaryText ? (
          <p className="text-gray-300 text-sm leading-relaxed">
            {commentaryText}
          </p>
        ) : (
          <p className="text-gray-500 text-sm italic">
            Commentary is being generated by ChainGPT AI...
          </p>
        )}

        {/* Footer */}
        <div className="flex items-center justify-between mt-4 pt-3 border-t border-gray-800/60">
          <div className="flex items-center gap-1.5">
            {/* ChainGPT logo placeholder — replace src with real logo */}
            <div className="w-5 h-5 rounded-full bg-gradient-to-br from-cyan-400 to-blue-600 flex items-center justify-center text-[10px] font-bold text-white">C</div>
            <span className="text-xs text-gray-500">Powered by <span className="text-cyan-400 font-semibold">ChainGPT AI</span></span>
          </div>
          {battle.resolved_at && (
            <span className="text-xs text-gray-700 font-mono">
              {new Date(battle.resolved_at + (battle.resolved_at.endsWith('Z') ? '' : 'Z')).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
            </span>
          )}
        </div>
      </div>

      {/* Bottom glow */}
      <div className="h-px bg-gradient-to-r from-transparent via-blue-500/30 to-transparent" />
    </div>
  );
}

export default BattleCommentary;
